stages:
  - build-image
  - build
  - test

build-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/base-builder.Containerfile"
      --destination "${CI_REGISTRY_IMAGE}/builder:latest"
  only:
    changes:
      - base-builder.Containerfile
  except:
    refs:
      - tags

build-linux:
  stage: build
  image: ${CI_REGISTRY_IMAGE}/builder:latest
  cache:
    - key: "linux-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-build"
      paths:
        - build
        - libs
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j4
  except:
    refs:
      - tags
  tags:
    - linux-local

test-linux:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/builder:latest
  cache:
    - key: "linux-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-build"
      paths:
        - build
        - libs
  script:
    - mkdir -p build
    - cd build
    - ctest
  except:
    refs:
      - tags
  tags:
    - linux-local
