stages:
  - build-image
  - build
  - test

.linux-cmake-template: &linux-cmake-config
  image: ${CI_REGISTRY_IMAGE}/builder:latest
  cache:
    - key: "linux-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-build"
      paths:
        - build
        - libs
  tags:
    - linux-local

build-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/base-builder.Containerfile" --destination "${CI_REGISTRY_IMAGE}/builder:latest"
  only:
    changes:
      - base-builder.Containerfile
  except:
    refs:
      - tags

build-linux:
  stage: build
  <<: *linux-cmake-config
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j4
  except:
    refs:
      - tags

test-linux:
  stage: test
  <<: *linux-cmake-config
  script:
    - cd build
    - ctest
  except:
    refs:
      - tags
