stages:
  - build-image
  - build
  - test
  - versionning
  - package
  - release

.linux-cmake-template: &linux-cmake-config
  image: ${CI_REGISTRY_IMAGE}/builder:latest
  cache:
    - key: "linux-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-build-0" #increment the number when you wanna clear the cmake cache out of a bug
      paths:
        - build
        - libs
  tags:
    - linux-local

build-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/base-builder.Containerfile" --destination "${CI_REGISTRY_IMAGE}/builder:latest"
  only:
    changes:
      - base-builder.Containerfile
  except:
    refs:
      - tags

build-linux:
  stage: build
  <<: *linux-cmake-config
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j4
  except:
    refs:
      - tags

test-linux:
  stage: test
  <<: *linux-cmake-config
  script:
    - cd build
    # we have to disable example and example64 tests from zlib...
    # our version of zlib does not yet include the january 2024 change
    # that allow to skip them in project where add_subdirectory is used to add zlib.
    - ctest -E "example"
  except:
    refs:
      - tags

versionning:
  image: node:21.7.3
  stage: versionning
  only:
    refs:
      - master
  script:
    - npm install @semantic-release/gitlab@13.0.3
    - npx semantic-release

linux-package:
  stage: package
  <<: *linux-cmake-config
  script:
    - cd build
    - make DESTDIR=./pkg install -j4
  except:
    refs:
      - tags

linux-release-archive:
  stage: release
  <<: *linux-cmake-config
  script:
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    - rm -rf package || true
    - mkdir package
    - make DESTDIR=./package/tree install -j4
    - cp ../res/linux_install.sh package/install.sh
    - cp ../res/linux_uninstall.sh package/uninstall.sh
    - cd package
    - tar -czvf kholors_${CI_COMMIT_TAG}.tar.gz *
  artifacts:
    paths:
      - build/kholors_${CI_COMMIT_TAG}.tar.gz
  except:
    refs:
      - tags
# all jobs after this stage (release) must use dependencies: [] to prevent download all artifacts
