#ifndef DEF_AUDIO_TRANSPORT_CONSTS_HPP
#define DEF_AUDIO_TRANSPORT_CONSTS_HPP

// Storage size of the audio segments.
#define AUDIO_SEGMENTS_BLOCK_SIZE 4096
#define MAXIMUM_TRACK_NAME_LENGTH 32

#endif