#pragma once

#define VISUAL_SAMPLE_RATE 48000
#define GRID_ALIGN_SAMPLE_POS_SHIFT 1920
#define MIN_SHOWABLE_RMS_VOLUME 0.01f
#define MAX_SHOWABLE_RMS_VOLUME 1.1f
#define MIN_DB -64.0f
#define MAX_DB 0.0f