#pragma once

#define DIALOG_FOOTER_AREA_HEIGHT 48
#define DIALOG_FOOTER_BUTTONS_SPACING 12
#define DIALOG_FOOTER_BUTTONS_WIDTH 90
#define DIALOG_FOOTER_BUTTONS_HEIGHT 28
#define DIALOG_TEXT_ENTRY_HEIGHT 30
#define DIALOG_TEXT_ENTRY_TOP_PADDING 8