#pragma once

#define AUDIO_SEGMENTS_BLOCK_SIZE 4096
#define MAXIMUM_TRACK_NAME_LENGTH 32
#define DEFAULT_CLIENT_BPM 120.0f
#define DEFAULT_TIME_SIGNATURE_NUMERATOR 4
#define DEFAULT_SERVER_PORT 8992
#define CLIENTS_DRAIN_PERIOD_MS 20