name: build_linux_image

on:
  push:
    branches:
      - "master"
    paths:
      - "base-builder.Containerfile"

jobs:
  build_linux_image:
    name: Build Linux Build Container and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase
        name: Lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base-builder.Containerfile
          push: true
          tags: ${{ steps.lowercase.outputs.lowercase }}/builder:latest
